# Generated by Django 4.0.6 on 2022-09-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_textpage_url_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpagesection',
            name='heading',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
