# Generated by Django 4.2.1 on 2023-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_navbarbutton_navbardropdown_navbardropdownitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpage',
            name='javascript',
            field=models.TextField(blank=True),
        ),
    ]
