# Generated by Django 4.2.1 on 2024-09-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_textpage_javascript'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialink',
            options={'ordering': ['name']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='navbardropdownitem',
            order_with_respect_to='dropdown',
        ),
        migrations.AlterOrderWithRespectTo(
            name='textpagesection',
            order_with_respect_to='page',
        ),
    ]
