# Generated by Django 4.2.1 on 2024-09-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_socialmedialink_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textpagesection',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='textpagesection',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterOrderWithRespectTo(
            name='textpagesection',
            order_with_respect_to=None,
        ),
    ]
