# Generated by Django 4.2.1 on 2024-09-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_textpagesection_options_textpagesection_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbardropdownitem',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='navbardropdownitem',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterOrderWithRespectTo(
            name='navbardropdownitem',
            order_with_respect_to=None,
        ),
    ]
