# Generated by Django 5.1.7 on 2025-04-08 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_navbardropdownitem_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "url_path",
                    models.CharField(
                        default="2025-04-08",
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("author", models.CharField(max_length=100)),
                ("content", models.TextField()),
            ],
            options={
                "ordering": ["creation_date"],
            },
        ),
    ]
